graph TD
  A["同伦类型论\nHOTT"]
  B["Lean"]
  C["Haskell"]
  D["Rust"]
  E["类型理论\nType Theory"]
  F["范畴论\nCategory Theory"]
  G["模型论\nModel Theory"]

  A -- "内建 Built-in" --> B
  A -- "理论模拟 Theoretical Modeling" --> C
  A -- "有限支持 Limited Support" --> D
  A -- "等价 Equivalence" --> E
  A -- "高阶结构 Higher Structure" --> F
  A -- "结构建模 Structure Modeling" --> G
  E -- "扩展 Extension" --> A
  F -- "高阶结构 Higher Structure" --> A
  G -- "结构建模 Structure Modeling" --> A 