graph TD
  A["时序类型理论\nTemporal Type Theory"]
  B["Haskell"]
  C["Rust"]
  D["Lean"]
  E["系统理论\nSystem Theory"]
  F["线性类型理论\nLinear Type Theory"]
  G["类型理论\nType Theory"]

  A -- "GADT/类型级编程 GADT/Type-level" --> B
  A -- "状态机 State Machine" --> C
  A -- "理论模拟 Theoretical Modeling" --> D
  A -- "动态建模 Dynamic Modeling" --> E
  A -- "资源建模 Resource Modeling" --> F
  G -- "扩展 Extension" --> A 